sudo: required

language: csharp

branches:
  only:
  - master

services:
  - docker

script:
    - docker build -t webapp:test -f ./Dockerfile .
    - docker run -it --rm -v $PWD/packages:/root/.nuget/packages webapp:test